// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erywidgxptocsficfoow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeXdpZGd4cHRvY3NmaWNmb293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwODkxMTksImV4cCI6MjA1NjY2NTExOX0.1uWMYSsBrtSC7um28jOtE0TfSXxvKxwx_mfc3hv1NzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);